"""initial migration

Revision ID: 0159b5e071a6
Revises: 2753e2b95d85
Create Date: 2026-08-23 20:12:29.077246

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0159b5e071a6'
down_revision: str | Sequence[str] | None = '2753e2b95d85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
