"""add missing fields to Event

Revision ID: 2753e2b95d85
Revises: 604f8d4cfcf4
Create Date: 2026-08-23 18:03:18.770534

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2753e2b95d85'
down_revision: str | Sequence[str] | None = '604f8d4cfcf4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
