"""add sync_meta and update event

Revision ID: 37cdaa69f92d
Revises: 
Create Date: 2026-08-22 16:42:40.067346

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '37cdaa69f92d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
