"""add tickets table

Revision ID: 604f8d4cfcf4
Revises: a486ec2d7726
Create Date: 2026-08-23 13:25:31.467030

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '604f8d4cfcf4'
down_revision: str | Sequence[str] | None = 'a486ec2d7726'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
