"""add tickets table

Revision ID: a486ec2d7726
Revises: 37cdaa69f92d
Create Date: 2026-08-23 13:24:36.886390

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a486ec2d7726'
down_revision: str | Sequence[str] | None = '37cdaa69f92d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
